stages:
  - check
  - publish

check_lint:
  stage: check
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - yarn install
    - yarn run check

publish_github:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - git pull
    - git push --force "https://${GITHUB_AUTH}@github.com/dwimm/plugin-bunq.git" --all
    - git push --force "https://${GITHUB_AUTH}@github.com/dwimm/plugin-bunq.git" --tags

publish_npm:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - npm run bump:production
    - npm publish
  only:
    - tags
