stages:
  - check
  - publish
  - notify

check_lint:
  stage: check
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - npm install
    - npm run check

publish_github:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - git pull
    - git push --force "https://${GITHUB_AUTH}@github.com/ubud-app/plugin-bunq.git" --all
    - git push --force "https://${GITHUB_AUTH}@github.com/ubud-app/plugin-bunq.git" --tags
  except:
    - tags

publish_npm:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - git push --force "https://${GITHUB_AUTH}@github.com/ubud-app/plugin-bunq.git" --tags
    - npm run bump
    - npm publish --access public
  only:
    - tags

notify:
  stage: notify
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - curl -X "POST" "https://beacon.ubud.club/webhooks/update-plugin/${WEBHOOK_SECRET}"
  only:
    - tags
